#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Feb 23, 2024 06:54:54 PM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #d9d9d9 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 
    wm focusmodel $top passive
    wm geometry $top 510x764+797+181
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa48" \
        -text "PIN panel" -width 480 -height 360 -style "frm.TLabelframe" \
        -style frm.TLabelframe 
    vTcl:DefineAlias "$top.tLa48" "frm_PIN" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa48
    ttk::button "$site_3_0.tBu47" \
        -text "1" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu47" "btn_PIN_01" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu48" \
        -text "2" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu48" "btn_PIN_02" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu50" \
        -text "3" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu50" "btn_PIN_03" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu52" \
        -text "4" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu52" "btn_PIN_04" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu53" \
        -text "5" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu53" "btn_PIN_05" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu54" \
        -text "6" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu54" "btn_PIN_06" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu55" \
        -text "7" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu55" "btn_PIN_07" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu59" \
        -text "C" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu59" "btn_PIN_C" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa54" \
        -background #ffffff -font "-family {Segoe UI} -size 9" -relief solid \
        -anchor w -justify left -compound left -style "lbl_PIN.TLabel" \
        -style lbl_PIN.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa54" "lbl_PIN_04" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa53" \
        -background #ffffff -font "-family {Segoe UI} -size 9" -relief solid \
        -anchor w -justify left -compound left -style "lbl_PIN.TLabel" \
        -style lbl_PIN.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa53" "lbl_PIN_03" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa52" \
        -background #ffffff -font "-family {Segoe UI} -size 9" -relief solid \
        -anchor w -justify left -compound left -style "lbl_PIN.TLabel" \
        -style lbl_PIN.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa52" "lbl_PIN_02" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa51" \
        -background #ffffff -font "-family {Segoe UI} -size 9" -relief solid \
        -anchor w -justify left -compound left -style "lbl_PIN.TLabel" \
        -style lbl_PIN.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa51" "lbl_PIN_01" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu62" \
        -text "CE" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu62" "btn_PIN_CE" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa55" \
        -background #ffffff -font "-family {Segoe UI} -size 9" -relief solid \
        -anchor n -justify left -text "Status i poruke" -compound left \
        -style "lbl_PIN_oznake.TLabel" -style lbl_PIN_oznake.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa55" "lbl_PIN_poruke" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu57" \
        -text "8" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu57" "btn_PIN_08" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu58" \
        -text "9" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu58" "btn_PIN_09" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu60" \
        -text "0" -compound left -style "btn_PIN.TButton" \
        -style btn_PIN.TButton 
    vTcl:DefineAlias "$site_3_0.tBu60" "btn_PIN_00" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.tBu47 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.264 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu48 \
        -in $site_3_0 -x 0 -relx 0.177 -y 0 -rely 0.264 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu50 \
        -in $site_3_0 -x 0 -relx 0.313 -y 0 -rely 0.264 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu52 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.444 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu53 \
        -in $site_3_0 -x 0 -relx 0.177 -y 0 -rely 0.444 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu54 \
        -in $site_3_0 -x 0 -relx 0.313 -y 0 -rely 0.444 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu55 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.625 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu59 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.806 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa54 \
        -in $site_3_0 -x 0 -relx 0.333 -y 0 -rely 0.083 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa53 \
        -in $site_3_0 -x 0 -relx 0.238 -y 0 -rely 0.083 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa52 \
        -in $site_3_0 -x 0 -relx 0.14 -y 0 -rely 0.083 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa51 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.083 -width 0 \
        -relwidth 0.081 -height 0 -relheight 0.108 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu62 \
        -in $site_3_0 -x 0 -relx 0.313 -y 0 -rely 0.806 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa55 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.083 -width 0 \
        -relwidth 0.5 -height 0 -relheight 0.861 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu57 \
        -in $site_3_0 -x 0 -relx 0.177 -y 0 -rely 0.625 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu58 \
        -in $site_3_0 -x 0 -relx 0.313 -y 0 -rely 0.625 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu60 \
        -in $site_3_0 -x 0 -relx 0.177 -y 0 -rely 0.806 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa47" \
        -text "Panel s gumbima" -width 480 -height 95 \
        -style "frm.TLabelframe" -style frm.TLabelframe 
    vTcl:DefineAlias "$top.tLa47" "frm_gumbi" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa47
    button "$site_3_0.but51" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "O" 
    vTcl:DefineAlias "$site_3_0.but51" "btn_otkljucaj" vTcl:WidgetProc "Toplevel1" 1
    button "$site_3_0.but50" \
        -activebackground #d9d9d9 -activeforeground black -background #d9d9d9 \
        -disabledforeground #a3a3a3 -font "-family {Segoe UI} -size 9" \
        -foreground #000000 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -text "Z" 
    vTcl:DefineAlias "$site_3_0.but50" "btn_pozvoni" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but51 \
        -in $site_3_0 -x 0 -relx 0.854 -y 0 -rely 0.3 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.3 -width 50 -relwidth 0 \
        -height 50 -relheight 0 -anchor nw -bordermode ignore 
    ::vTcl::widgets::ttk::labelframe::createCmd "$top.tLa49" \
        -text "Upravljanje dodijeljenim kljucevima" -width 480 -height 246 \
        -style "frm.TLabelframe" -style frm.TLabelframe 
    vTcl:DefineAlias "$top.tLa49" "frm_DB" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tLa49
    ttk::button "$site_3_0.tBu81" \
        -text "Odustani" -compound left -style "btn_unos.TButton" \
        -style btn_unos.TButton 
    vTcl:DefineAlias "$site_3_0.tBu81" "btn_odustani" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu82" \
        -text "Izbrisi" -compound left -style "btn_unos.TButton" \
        -style btn_unos.TButton 
    vTcl:DefineAlias "$site_3_0.tBu82" "btn_izbrisi" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn78" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam \
        -style "ent_unos.TEntry" -style ent_unos.TEntry 
    vTcl:DefineAlias "$site_3_0.tEn78" "ent_PIN" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn77" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam \
        -style "ent_unos.TEntry" -style ent_unos.TEntry 
    vTcl:DefineAlias "$site_3_0.tEn77" "ent_prezime" vTcl:WidgetProc "Toplevel1" 1
    ttk::entry "$site_3_0.tEn76" \
        -font "-family {Segoe UI} -size 9" -cursor ibeam \
        -style "ent_unos.TEntry" -style ent_unos.TEntry 
    vTcl:DefineAlias "$site_3_0.tEn76" "ent_ime" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa73" \
        -font "-family {Segoe UI} -size 9" -relief flat -anchor w \
        -justify left -text "Ime:" -compound left -style "lbl_unos.TLabel" \
        -style lbl_unos.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa73" "lbl_ime" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa72" \
        -font "-family {Segoe UI} -size 9" -relief flat -anchor w \
        -justify left -text "Prezime:" -compound left \
        -style "lbl_unos.TLabel" -style lbl_unos.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa72" "lbl_prezime" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa74" \
        -font "-family {Segoe UI} -size 9" -relief flat -anchor w \
        -justify left -text "PIN:" -compound left -style "lbl_unos.TLabel" \
        -style lbl_unos.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa74" "lbl_PIN" vTcl:WidgetProc "Toplevel1" 1
    ttk::label "$site_3_0.tLa75" \
        -font "-family {Segoe UI} -size 9" -relief flat -anchor w \
        -justify left -text "Aktivan:" -compound left \
        -style "lbl_unos.TLabel" -style lbl_unos.TLabel 
    vTcl:DefineAlias "$site_3_0.tLa75" "lbl_aktivan" vTcl:WidgetProc "Toplevel1" 1
    ttk::checkbutton "$site_3_0.tCh79" \
        -variable "tch79" -compound left -style "" 
    vTcl:DefineAlias "$site_3_0.tCh79" "chk_aktivan" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$site_3_0.tBu80" \
        -text "Spremi" -compound left -style "btn_unos.TButton" \
        -style btn_unos.TButton 
    vTcl:DefineAlias "$site_3_0.tBu80" "btn_spremi" vTcl:WidgetProc "Toplevel1" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_3_0.scr71" \
        -background #d9d9d9 -height 75 -highlightbackground #d9d9d9 \
        -highlightcolor #000000 -width 125 
    vTcl:DefineAlias "$site_3_0.scr71" "box_korisnici" vTcl:WidgetProc "Toplevel1" 1

    $site_3_0.scr71.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 10" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -relief solid \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    place $site_3_0.tBu81 \
        -in $site_3_0 -x 0 -relx 0.635 -y 0 -rely 0.813 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tBu82 \
        -in $site_3_0 -x 0 -relx 0.813 -y 0 -rely 0.813 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tEn78 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.366 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn77 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tEn76 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.122 -width 0 \
        -relwidth 0.333 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa73 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.122 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.11 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa72 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.244 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.11 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa74 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.366 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.11 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tLa75 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.125 -height 0 -relheight 0.11 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCh79 \
        -in $site_3_0 -x 0 -relx 0.625 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.135 -height 0 -relheight 0.118 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tBu80 \
        -in $site_3_0 -x 0 -relx 0.458 -y 0 -rely 0.813 -width 70 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr71 \
        -in $site_3_0 -x 0 -relx 0.042 -y 0 -rely 0.122 -width 0 \
        -relwidth 0.375 -height 0 -relheight 0.813 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa48 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.164 -width 0 -relwidth 0.941 \
        -height 0 -relheight 0.471 -anchor nw -bordermode ignore 
    place $top.tLa47 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.013 -width 0 -relwidth 0.941 \
        -height 0 -relheight 0.131 -anchor nw -bordermode ignore 
    place $top.tLa49 \
        -in $top -x 0 -relx 0.029 -y 0 -rely 0.654 -width 0 -relwidth 0.941 \
        -height 0 -relheight 0.322 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

