#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Mar 24, 2024 02:22:37 AM CET  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

# _location = os.path.dirname(__file__)

# import MeteoLayout10_support

# _bgcolor = 'SystemButtonFace'
# _fgcolor = 'SystemWindowText'
# _tabfg1 = 'black' 
# _tabfg2 = 'white' 
# _bgmode = 'light' 
# _tabbg1 = '#d9d9d9' 
# _tabbg2 = 'gray40' 

# _style_code_ran = 0
# def _style_code():
#     global _style_code_ran
#     if _style_code_ran: return        
#     try: MeteoLayout10_support.root.tk.call('source',
#                 os.path.join(_location, 'themes', 'xpnative.tcl'))
#     except: pass
#     style = ttk.Style()
#     style.theme_use('xpnative')
#     style.configure('.', font = "TkDefaultFont")
#     _style_code_ran = 1

class prognoza:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("430x680+788+241")
        top.minsize(120, 1)
        top.maxsize(3844, 1061)
        top.resizable(1,  1)
        top.title("PROGNOZA")
        top.configure(highlightcolor="SystemWindowText")

        self.top = top

        _style_code()
        self.frm_temp = ttk.Labelframe(self.top)
        self.frm_temp.place(relx=0.035, rely=0.015, relheight=0.368
                , relwidth=0.93)
        self.frm_temp.configure(relief='')
        self.frm_temp.configure(text='''Temperatura [C]''')
        self.frm_temp.configure(style='frm.TLabelframe')

        self.lbl_temp_kuca_unutra = ttk.Label(self.frm_temp)
        self.lbl_temp_kuca_unutra.place(relx=0.6, rely=0.4, height=22, width=100
                , bordermode='ignore')
        self.lbl_temp_kuca_unutra.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_kuca_unutra.configure(relief="flat")
        self.lbl_temp_kuca_unutra.configure(anchor='w')
        self.lbl_temp_kuca_unutra.configure(justify='left')
        self.lbl_temp_kuca_unutra.configure(text='''Unutar kuće:''')
        self.lbl_temp_kuca_unutra.configure(compound='left')
        self.lbl_temp_kuca_unutra.configure(style='lbl_unos.TLabel')

        self.lbl_temp_kuca_unutra_v = ttk.Label(self.frm_temp)
        self.lbl_temp_kuca_unutra_v.place(relx=0.6, rely=0.48, height=40
                , width=100, bordermode='ignore')
        self.lbl_temp_kuca_unutra_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_temp_kuca_unutra_v.configure(relief="flat")
        self.lbl_temp_kuca_unutra_v.configure(anchor='w')
        self.lbl_temp_kuca_unutra_v.configure(justify='left')
        self.lbl_temp_kuca_unutra_v.configure(text='''+ 00''')
        self.lbl_temp_kuca_unutra_v.configure(compound='left')
        self.lbl_temp_kuca_unutra_v.configure(style='lbl_unos.TLabel')

        self.lbl_temp_grad_v = ttk.Label(self.frm_temp)
        self.lbl_temp_grad_v.place(relx=0.6, rely=0.16, height=40, width=100
                , bordermode='ignore')
        self.lbl_temp_grad_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_temp_grad_v.configure(relief="flat")
        self.lbl_temp_grad_v.configure(anchor='w')
        self.lbl_temp_grad_v.configure(justify='left')
        self.lbl_temp_grad_v.configure(text='''+ 00''')
        self.lbl_temp_grad_v.configure(compound='left')
        self.lbl_temp_grad_v.configure(style='lbl_unos.TLabel')

        self.lbl_temp_kuca_ugoda = ttk.Label(self.frm_temp)
        self.lbl_temp_kuca_ugoda.place(relx=0.038, rely=0.08, height=22
                , width=100, bordermode='ignore')
        self.lbl_temp_kuca_ugoda.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_kuca_ugoda.configure(relief="flat")
        self.lbl_temp_kuca_ugoda.configure(anchor='w')
        self.lbl_temp_kuca_ugoda.configure(justify='left')
        self.lbl_temp_kuca_ugoda.configure(text='''Osjećaj ugode:''')
        self.lbl_temp_kuca_ugoda.configure(compound='left')
        self.lbl_temp_kuca_ugoda.configure(style='lbl_unos.TLabel')

        self.lbl_temp_grad = ttk.Label(self.frm_temp)
        self.lbl_temp_grad.place(relx=0.6, rely=0.08, height=22, width=100
                , bordermode='ignore')
        self.lbl_temp_grad.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_grad.configure(relief="flat")
        self.lbl_temp_grad.configure(anchor='w')
        self.lbl_temp_grad.configure(justify='left')
        self.lbl_temp_grad.configure(text='''Ref. postaja:''')
        self.lbl_temp_grad.configure(compound='left')
        self.lbl_temp_grad.configure(style='lbl_unos.TLabel')

        self.lbl_temp_kuca_vani_v = ttk.Label(self.frm_temp)
        self.lbl_temp_kuca_vani_v.place(relx=0.6, rely=0.8, height=40, width=100
                , bordermode='ignore')
        self.lbl_temp_kuca_vani_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_temp_kuca_vani_v.configure(relief="flat")
        self.lbl_temp_kuca_vani_v.configure(anchor='w')
        self.lbl_temp_kuca_vani_v.configure(justify='left')
        self.lbl_temp_kuca_vani_v.configure(text='''+ 00''')
        self.lbl_temp_kuca_vani_v.configure(compound='left')
        self.lbl_temp_kuca_vani_v.configure(style='lbl_unos.TLabel')

        self.box_temperatura = ScrolledListBox(self.frm_temp)
        self.box_temperatura.place(relx=0.038, rely=0.42, relheight=0.52
                , relwidth=0.45, bordermode='ignore')
        self.box_temperatura.configure(background="SystemButtonFace")
        self.box_temperatura.configure(cursor="xterm")
        self.box_temperatura.configure(disabledforeground="#b4b4b4")
        self.box_temperatura.configure(font="-family {Segoe UI} -size 10")
        self.box_temperatura.configure(foreground="SystemWindowText")
        self.box_temperatura.configure(highlightcolor="#d9d9d9")
        self.box_temperatura.configure(relief="solid")
        self.box_temperatura.configure(selectbackground="#d9d9d9")
        self.box_temperatura.configure(selectforeground="black")

        self.lbl_temp_kuca_vani = ttk.Label(self.frm_temp)
        self.lbl_temp_kuca_vani.place(relx=0.6, rely=0.72, height=22, width=100
                , bordermode='ignore')
        self.lbl_temp_kuca_vani.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_kuca_vani.configure(relief="flat")
        self.lbl_temp_kuca_vani.configure(anchor='w')
        self.lbl_temp_kuca_vani.configure(justify='left')
        self.lbl_temp_kuca_vani.configure(text='''Izvan kuće:''')
        self.lbl_temp_kuca_vani.configure(compound='left')
        self.lbl_temp_kuca_vani.configure(style='lbl_unos.TLabel')

        self.lbl_temp_ugoda_1 = ttk.Label(self.frm_temp)
        self.lbl_temp_ugoda_1.place(relx=0.038, rely=0.2, height=39, width=39
                , bordermode='ignore')
        self.lbl_temp_ugoda_1.configure(background="#ffffff")
        self.lbl_temp_ugoda_1.configure(font="TkDefaultFont")
        self.lbl_temp_ugoda_1.configure(borderwidth="1")
        self.lbl_temp_ugoda_1.configure(relief="solid")
        self.lbl_temp_ugoda_1.configure(anchor='center')
        self.lbl_temp_ugoda_1.configure(justify='left')
        self.lbl_temp_ugoda_1.configure(compound='left')

        self.lbl_temp_ugoda_2 = ttk.Label(self.frm_temp)
        self.lbl_temp_ugoda_2.place(relx=0.155, rely=0.2, height=39, width=39
                , bordermode='ignore')
        self.lbl_temp_ugoda_2.configure(background="#ffffff")
        self.lbl_temp_ugoda_2.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_ugoda_2.configure(borderwidth="1")
        self.lbl_temp_ugoda_2.configure(relief="solid")
        self.lbl_temp_ugoda_2.configure(anchor='center')
        self.lbl_temp_ugoda_2.configure(justify='left')
        self.lbl_temp_ugoda_2.configure(compound='left')

        self.lbl_temp_ugoda_3 = ttk.Label(self.frm_temp)
        self.lbl_temp_ugoda_3.place(relx=0.273, rely=0.2, height=39, width=39
                , bordermode='ignore')
        self.lbl_temp_ugoda_3.configure(background="#ffffff")
        self.lbl_temp_ugoda_3.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_ugoda_3.configure(borderwidth="1")
        self.lbl_temp_ugoda_3.configure(relief="solid")
        self.lbl_temp_ugoda_3.configure(anchor='center')
        self.lbl_temp_ugoda_3.configure(justify='left')
        self.lbl_temp_ugoda_3.configure(compound='left')

        self.lbl_temp_ugoda_4 = ttk.Label(self.frm_temp)
        self.lbl_temp_ugoda_4.place(relx=0.39, rely=0.2, height=39, width=39
                , bordermode='ignore')
        self.lbl_temp_ugoda_4.configure(background="#ffffff")
        self.lbl_temp_ugoda_4.configure(font="-family {Segoe UI} -size 9")
        self.lbl_temp_ugoda_4.configure(borderwidth="1")
        self.lbl_temp_ugoda_4.configure(relief="solid")
        self.lbl_temp_ugoda_4.configure(anchor='center')
        self.lbl_temp_ugoda_4.configure(justify='left')
        self.lbl_temp_ugoda_4.configure(compound='left')
        self.lbl_temp_ugoda_4.configure(cursor="fleur")

        self.frm_vlaznost = ttk.Labelframe(self.top)
        self.frm_vlaznost.place(relx=0.035, rely=0.397, relheight=0.25
                , relwidth=0.93)
        self.frm_vlaznost.configure(relief='')
        self.frm_vlaznost.configure(text='''Vlažnost [%]''')
        self.frm_vlaznost.configure(style='frm.TLabelframe')

        self.lbl_vlaga_kuca_unutra = ttk.Label(self.frm_vlaznost)
        self.lbl_vlaga_kuca_unutra.place(relx=0.6, rely=0.118, height=22
                , width=100, bordermode='ignore')
        self.lbl_vlaga_kuca_unutra.configure(font="-family {Segoe UI} -size 9")
        self.lbl_vlaga_kuca_unutra.configure(relief="flat")
        self.lbl_vlaga_kuca_unutra.configure(anchor='w')
        self.lbl_vlaga_kuca_unutra.configure(justify='left')
        self.lbl_vlaga_kuca_unutra.configure(text='''Unutar kuće:''')
        self.lbl_vlaga_kuca_unutra.configure(compound='left')
        self.lbl_vlaga_kuca_unutra.configure(style='lbl_unos.TLabel')

        self.lbl_vlaga_kuca_unutra_v = ttk.Label(self.frm_vlaznost)
        self.lbl_vlaga_kuca_unutra_v.place(relx=0.6, rely=0.235, height=40
                , width=100, bordermode='ignore')
        self.lbl_vlaga_kuca_unutra_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_vlaga_kuca_unutra_v.configure(relief="flat")
        self.lbl_vlaga_kuca_unutra_v.configure(anchor='w')
        self.lbl_vlaga_kuca_unutra_v.configure(justify='left')
        self.lbl_vlaga_kuca_unutra_v.configure(text='''00''')
        self.lbl_vlaga_kuca_unutra_v.configure(compound='left')
        self.lbl_vlaga_kuca_unutra_v.configure(style='lbl_unos.TLabel')

        self.lbl_vlaga_kuca_vani_v = ttk.Label(self.frm_vlaznost)
        self.lbl_vlaga_kuca_vani_v.place(relx=0.6, rely=0.706, height=40
                , width=100, bordermode='ignore')
        self.lbl_vlaga_kuca_vani_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_vlaga_kuca_vani_v.configure(relief="flat")
        self.lbl_vlaga_kuca_vani_v.configure(anchor='w')
        self.lbl_vlaga_kuca_vani_v.configure(justify='left')
        self.lbl_vlaga_kuca_vani_v.configure(text='''00''')
        self.lbl_vlaga_kuca_vani_v.configure(compound='left')
        self.lbl_vlaga_kuca_vani_v.configure(style='lbl_unos.TLabel')

        self.box_vlaga = ScrolledListBox(self.frm_vlaznost)
        self.box_vlaga.place(relx=0.038, rely=0.147, relheight=0.765
                , relwidth=0.45, bordermode='ignore')
        self.box_vlaga.configure(background="SystemButtonFace")
        self.box_vlaga.configure(cursor="xterm")
        self.box_vlaga.configure(disabledforeground="#b4b4b4")
        self.box_vlaga.configure(font="-family {Segoe UI} -size 10")
        self.box_vlaga.configure(foreground="SystemWindowText")
        self.box_vlaga.configure(highlightcolor="#d9d9d9")
        self.box_vlaga.configure(relief="solid")
        self.box_vlaga.configure(selectbackground="#d9d9d9")
        self.box_vlaga.configure(selectforeground="black")

        self.lbl_vlaga_kuca_vani = ttk.Label(self.frm_vlaznost)
        self.lbl_vlaga_kuca_vani.place(relx=0.6, rely=0.588, height=22, width=100
                , bordermode='ignore')
        self.lbl_vlaga_kuca_vani.configure(font="-family {Segoe UI} -size 9")
        self.lbl_vlaga_kuca_vani.configure(relief="flat")
        self.lbl_vlaga_kuca_vani.configure(anchor='w')
        self.lbl_vlaga_kuca_vani.configure(justify='left')
        self.lbl_vlaga_kuca_vani.configure(text='''Izvan kuće:''')
        self.lbl_vlaga_kuca_vani.configure(compound='left')
        self.lbl_vlaga_kuca_vani.configure(style='lbl_unos.TLabel')

        self.frm_tlak = ttk.Labelframe(self.top)
        self.frm_tlak.place(relx=0.035, rely=0.662, relheight=0.25
                , relwidth=0.93)
        self.frm_tlak.configure(relief='')
        self.frm_tlak.configure(text='''Tlak [kPa]''')
        self.frm_tlak.configure(style='frm.TLabelframe')

        self.lbl_tlak_kuca_unutra = ttk.Label(self.frm_tlak)
        self.lbl_tlak_kuca_unutra.place(relx=0.6, rely=0.118, height=22
                , width=100, bordermode='ignore')
        self.lbl_tlak_kuca_unutra.configure(font="-family {Segoe UI} -size 9")
        self.lbl_tlak_kuca_unutra.configure(relief="flat")
        self.lbl_tlak_kuca_unutra.configure(anchor='w')
        self.lbl_tlak_kuca_unutra.configure(justify='left')
        self.lbl_tlak_kuca_unutra.configure(text='''Unutar kuće:''')
        self.lbl_tlak_kuca_unutra.configure(compound='left')
        self.lbl_tlak_kuca_unutra.configure(style='lbl_unos.TLabel')

        self.lbl_tlak_kuca_unutra_v = ttk.Label(self.frm_tlak)
        self.lbl_tlak_kuca_unutra_v.place(relx=0.6, rely=0.235, height=40
                , width=100, bordermode='ignore')
        self.lbl_tlak_kuca_unutra_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_tlak_kuca_unutra_v.configure(relief="flat")
        self.lbl_tlak_kuca_unutra_v.configure(anchor='w')
        self.lbl_tlak_kuca_unutra_v.configure(justify='left')
        self.lbl_tlak_kuca_unutra_v.configure(text='''0000''')
        self.lbl_tlak_kuca_unutra_v.configure(compound='left')
        self.lbl_tlak_kuca_unutra_v.configure(style='lbl_unos.TLabel')

        self.lbl_tlak_kuca_vani_v = ttk.Label(self.frm_tlak)
        self.lbl_tlak_kuca_vani_v.place(relx=0.6, rely=0.706, height=40
                , width=100, bordermode='ignore')
        self.lbl_tlak_kuca_vani_v.configure(font="-family {Segoe UI} -size 18")
        self.lbl_tlak_kuca_vani_v.configure(relief="flat")
        self.lbl_tlak_kuca_vani_v.configure(anchor='w')
        self.lbl_tlak_kuca_vani_v.configure(justify='left')
        self.lbl_tlak_kuca_vani_v.configure(text='''0000''')
        self.lbl_tlak_kuca_vani_v.configure(compound='left')
        self.lbl_tlak_kuca_vani_v.configure(style='lbl_unos.TLabel')

        self.box_tlak = ScrolledListBox(self.frm_tlak)
        self.box_tlak.place(relx=0.038, rely=0.147, relheight=0.765
                , relwidth=0.45, bordermode='ignore')
        self.box_tlak.configure(background="SystemButtonFace")
        self.box_tlak.configure(cursor="xterm")
        self.box_tlak.configure(disabledforeground="#b4b4b4")
        self.box_tlak.configure(font="-family {Segoe UI} -size 10")
        self.box_tlak.configure(foreground="SystemWindowText")
        self.box_tlak.configure(highlightcolor="#d9d9d9")
        self.box_tlak.configure(relief="solid")
        self.box_tlak.configure(selectbackground="#d9d9d9")
        self.box_tlak.configure(selectforeground="black")

        self.lbl_tlak_kuca_vani = ttk.Label(self.frm_tlak)
        self.lbl_tlak_kuca_vani.place(relx=0.6, rely=0.588, height=22, width=100
                , bordermode='ignore')
        self.lbl_tlak_kuca_vani.configure(font="-family {Segoe UI} -size 9")
        self.lbl_tlak_kuca_vani.configure(relief="flat")
        self.lbl_tlak_kuca_vani.configure(anchor='w')
        self.lbl_tlak_kuca_vani.configure(justify='left')
        self.lbl_tlak_kuca_vani.configure(text='''Izvan kuće:''')
        self.lbl_tlak_kuca_vani.configure(compound='left')
        self.lbl_tlak_kuca_vani.configure(style='lbl_unos.TLabel')

        self.btn_spremi = ttk.Button(self.top)
        self.btn_spremi.place(relx=0.035, rely=0.934, height=30, width=75)
        self.btn_spremi.configure(text='''Spremi''')
        self.btn_spremi.configure(compound='left')
        self.btn_spremi.configure(style='btn_unos.TButton')

        self.btn_izbrisi = ttk.Button(self.top)
        self.btn_izbrisi.place(relx=0.233, rely=0.934, height=30, width=75)
        self.btn_izbrisi.configure(text='''Izbriši''')
        self.btn_izbrisi.configure(compound='left')
        self.btn_izbrisi.configure(style='btn_unos.TButton')

        self.btn_pokreni = ttk.Button(self.top)
        self.btn_pokreni.place(relx=0.593, rely=0.934, height=30, width=75)
        self.btn_pokreni.configure(text='''Pokreni''')
        self.btn_pokreni.configure(compound='left')
        self.btn_pokreni.configure(style='btn_unos.TButton')

        self.btn_zaustavi = ttk.Button(self.top)
        self.btn_zaustavi.place(relx=0.791, rely=0.934, height=30, width=75)
        self.btn_zaustavi.configure(text='''Zaustavi''')
        self.btn_zaustavi.configure(compound='left')
        self.btn_zaustavi.configure(style='btn_unos.TButton')