USE GST
GO

SELECT * INTO [dbo].[FTLin]
FROM [dbo].[FTL];
SELECT * INTO [dbo].[NONFTLin]
FROM [dbo].[NONFTL];

ALTER TABLE [dbo].[FTLin] ADD FTLtype VARCHAR(10)
ALTER TABLE [dbo].[NONFTLin] ADD FTLtype VARCHAR(10)

UPDATE [dbo].[FTLin] SET FTLtype = 'FTL'
UPDATE [dbo].[NONFTLin] SET FTLtype = 'NONFTL'

SELECT * INTO FTLjoin FROM FTLin UNION SELECT * FROM NONFTLin;

SELECT [PLU],[CATEGORY],[COMMODITY],[FTLtype] FROM FTLjoin ORDER BY [PLU]

DROP TABLE FTLin;
DROP TABLE NONFTLin;
